* Introduction
  This example shows how links and references works.
  Every link is clickable!

* Sections
  You can add a reference to section [[*Introduction]].

* Equations
  You can refer to equation [[eqn:phi]].
  #+Name: eqn:phi
  \begin{equation}
  \phi = \frac{2\pi fD}{c}
  \end{equation}

* Tables
  Reference to table [[anchor_table]].
  Caption is required for the reference to work properly.

  #+NAME: anchor_table
  #+CAPTION: a nice table
  | Anchor |   MAE |
  |--------+-------|
  | a1     | 6.871 |
  | a2     | 5.275 |
  | a3     | 5.406 |

* items
  1. one item
  2. <<target>>another item
  Here we refer to item [[target]].

* links
  Visit the [[https://orgmode.org/][official org mode website]].

* manual link
  # source: https://www.overleaf.com/learn/latex/Hyperlinks

  It's also possible to link directly any word
  or \hyperlink{thesentence}{any sentence} in you document.

  If you read this text, you will get no information.  Really?
  Is there no information?

  For instance \hypertarget{thesentence}{this sentence}.
