* Introduction
  This example shows what you can do with a one line =header.tex= file.

** subsection
   This text is a inside subsection. You can refer to other sections, like section [[Introduction]].

* some code
  Even if you specify the programming language, code syntax is not highlighted
  by default.

  #+begin_src c -n -r
    int main()
    {
        printf("hello world\n"); (ref:print_c)
  #+end_src

  In line [[(print_c)]] you print =hello world= to =stdout=.
  #+begin_src c +n -r
        int a = 1 + 2; (ref:example_sum)
    }
  #+end_src

  In line [[(example_sum)]] you just do an assignment.

** python code
  #+begin_src python
    # This program prints Hello, world!
    print('Hello, world!')
  #+end_src

* lists
** numerated
   1. one
   2. two
      1. sub-two
         1. sub-sub-two
   3. three

** unnumerated
   - One
     - Two
       - Three
         - Four

*** trivia
    Doc-org could mean a lot of things, such as:
    - document - organized
    - docker - org mode
    - docile - organist
    A team of 42 linguists is currently searching for the answer.

* Some math
  You can insert latex equation, like equation [[eqn:phi]].
  #+Name: eqn:phi
  \begin{equation}
  \phi = \frac{2\pi fD}{c}
  \end{equation}

  As you can see, reference to equations works by default, but see =references=
  example if you want links to be clickable.

** Other latex equations
   Equation [[eqn:phase_range]] reference.

   #+Name: eqn:phase_range
   \begin{equation}
   D = \frac{c\phi}{2\pi f}
   \end{equation}

*** A more complicated equation

    \begin{equation}
    \Delta TOF_{est} = \frac{k_T TOF}{1+k_T } - 0.5 \frac{\mu_A' - \mu_T'}{1+k_T}.
    \end{equation}
