name: CI

on:
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: download doc-org
      run: git clone https://github.com/doc-org/doc-org
    - name: build demo1
      run: |
        cd demo1
        ../doc-org/doc-org
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./demo1/build
      with:
        emptyCommits: false
