name: CI

on:
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: download doc-org
      run: git clone https://github.com/doc-org/doc-org
    - name: build demo1
      run: |
        examples=(*/)
        mkdir deploy
        for dir in $examples; do
          mkdir deploy/$dir
          cd $dir
          ../doc-org/doc-org
          whoami
          ls -al
          sudo mv build/*.pdf build/*.tex ../deploy/$dir
          cd ..
        done
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./deploy
      with:
        emptyCommits: false
