name: CI

on:
  push:	
    branches:	
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: download doc-org
      run: git clone https://github.com/doc-org/doc-org
    - name: build demo1
      run: |
        ls
        cd demo1
        ../doc-org/doc-org
