name: Deploy

on:
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: download doc-org
      run: git clone https://github.com/doc-org/doc-org
    - name: run doc org
      run: |
        examples=(*/)
        mkdir deploy
        for dir in $examples; do
          mkdir deploy/$dir
          cd $dir
          ../doc-org/doc-org

          # give current user ownership of the build directory
          current_user=$(whoami)
          sudo chown -R $current_user build

          mv build/*.pdf build/*.tex ../deploy/$dir
          cd ..
        done
    - name: build website
      run: |
        echo "<!DOCTYPE HTML>
        <html>
        <head>
            <meta charset="utf-8" />
            <title>Doc-Org Examples</title>
        </head>
        <body>" >> deploy/index.html

        whoami
        ls -al
        for dir in deploy/*/; do
          ls -al $dir
          echo "<h1>$dir</h1>
              <ul>" >> deploy/index.html
          files=$(ls $dir)
          echo files:
          echo $files
          for file in $files; do
            echo "        <li><a href=\"$directory$file\">$file</a></li>" >> deploy/index.html
          done
          echo "    </ul>" >> deploy/index.html
        done
        echo "</body></html>" >> deploy/index.html
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./deploy
      with:
        emptyCommits: false
