name: Deploy

on:
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: run doc org
      run: |
        examples=$(ls -d */)
        echo "$examples"
        git clone https://github.com/doc-org/doc-org
        mkdir deploy
        for dir in $examples; do
          mkdir deploy/$dir
          echo "process directory "$dir""
          ls "$dir"
          ./doc-org/doc-org "$dir"

          # give current user ownership of the build directory
          current_user=$(whoami)
          sudo chown -R $current_user "$dir"/build

          mv "$dir"/build/*.pdf "$dir"/build/*.tex deploy/$dir
        done
    - name: build website
      run: |
        echo "<!DOCTYPE HTML>
        <html>
        <head>
            <meta charset="utf-8" />
            <title>Doc-Org Examples</title>
        </head>
        <body>
        <h1>Doc-Org Examples</h1>
        Examples input <a href=\"https://github.com/doc-org/examples\">here</a>. Examples output:" >> deploy/index.html

        for dir in deploy/*/; do
          dir_basename=$(basename "$dir")
          echo "<h2>"$dir_basename"</h1>
              <ul>" >> deploy/index.html

          # for each file in the directory
          ls -1 "$dir" | while read file ; do
            echo "        <li><a href=\""$dir_basename"/"$file"\">"$file"</a></li>" >> deploy/index.html
          done
          echo "    </ul>" >> deploy/index.html
        done
        echo "</body></html>" >> deploy/index.html
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./deploy
        publish_branch: gh-pages
        emptyCommits: false
